In [1]:
#drop player that is out

In [2]:
import pandas as pd 
import numpy as np
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import cross_val_score

import matplotlib.pyplot as plt

In [3]:
dates_all = [
    ['3_11', '2020-03-11'],
    ['3_10', '2020-03-10'],
    ['3_9', '2020-03-09'],
    ['3_8', '2020-03-08'],
    ['3_7', '2020-03-07'],
    ['3_6', '2020-03-06'],
    ['3_5', '2020-03-05'],
    ['3_4', '2020-03-04'],
    ['3_3', '2020-03-03'],
    ['3_2', '2020-03-02'],
    ['3_1', '2020-03-01'],
    ['2_29', '2020-02-29'],
    ['2_28', '2020-02-28'],
    ['2_27', '2020-02-27'],
    ['2_26', '2020-02-26'],
    ['2_25', '2020-02-25'],
    ['2_24', '2020-02-24'],
    ['2_23', '2020-02-23'],
    ['2_22', '2020-02-22'],
    ['2_21', '2020-02-21'],
    ['2_20', '2020-02-20'],
    ['2_13', '2020-02-13'],
    ['2_12', '2020-02-12'],
    ['2_11', '2020-02-11'],
    ['2_10', '2020-02-10'],
    ['2_9', '2020-02-09'],
    ['2_8', '2020-02-08'],
    ['2_7', '2020-02-07'],
    ['2_6', '2020-02-06'],
    ['2_5', '2020-02-05'],
    ['2_4', '2020-02-04'],
    ['2_3', '2020-02-03'],
    ['2_2', '2020-02-02'],
    ['2_1', '2020-02-01'],
    ['1_31', '2020-01-31'],
    ['1_30', '2020-01-30'],
    ['1_29', '2020-01-29'],
    ['1_28', '2020-01-28'],
    ['1_27', '2020-01-27'],
    ['1_26', '2020-01-26'],
    ['1_25', '2020-01-25'],
    ['1_24', '2020-01-24'],
    ['1_23', '2020-01-23'],
    ['1_22', '2020-01-22'],
    ['1_20', '2020-01-20'],
    ['1_19', '2020-01-19'],
    ['1_18', '2020-01-18'],
    ['1_17', '2020-01-17'],
    ['1_16', '2020-01-16'],
    ['1_15', '2020-01-15'],
    ['1_14', '2020-01-14'],
    ['1_13', '2020-01-13'],
    ['1_12', '2020-01-12'],
    ['1_11', '2020-01-11'],
    ['1_10', '2020-01-10'],
    ['1_9', '2020-01-09'],
    ['1_8', '2020-01-08'],
    ['1_7', '2020-01-07'],
    ['1_6', '2020-01-06'],
    ['1_5', '2020-01-05'],
    ['1_4', '2020-01-04'],
    ['1_3', '2020-01-03'],
    ['1_2', '2020-01-02'],
    ['1_1', '2020-01-01'],
    ['12_31', '2019-12-31'],
    ['12_30', '2019-12-30'],
    ['12_29', '2019-12-29'],
    ['12_28', '2019-12-28'],
    ['12_27', '2019-12-27'],
    ['12_26', '2019-12-26'],
    ['12_25', '2019-12-25'],
    ['12_23', '2019-12-23'],
    ['12_22', '2019-12-22'],
    ['12_21', '2019-12-21'],
    ['12_20', '2019-12-20'],
    ['12_19', '2019-12-19'],
    ['12_18', '2019-12-18'],
    ['12_17', '2019-12-17'],
    ['12_16', '2019-12-16'],
    ['12_15', '2019-12-15'],
    ['12_14', '2019-12-14'],
    ['12_13', '2019-12-13'],
    ['12_12', '2019-12-12'],
    ['12_11', '2019-12-11'],
    ['12_10', '2019-12-10'],
    ['12_9', '2019-12-09'],
    ['12_8', '2019-12-08'],
    ['12_7', '2019-12-07'],
    ['12_6', '2019-12-06'],
    ['12_5', '2019-12-05'],
    ['12_4', '2019-12-04'],
    ['12_3', '2019-12-03'],
    ['12_2', '2019-12-02'],
    ['12_1', '2019-12-01'],
    ['11_30', '2019-11-30'],
    ['11_29', '2019-11-29'],
    ['11_27', '2019-11-27'],
    ['11_26', '2019-11-26'],
    ['11_25', '2019-11-25'],
    ['11_24', '2019-11-24'],
    ['11_23', '2019-11-23'],
    ['11_22', '2019-11-22'],
    ['11_21', '2019-11-21'],
    ['11_20', '2019-11-20'],
    ['11_19', '2019-11-19'],
    ['11_18', '2019-11-18'],
    ['11_17', '2019-11-17'],
    ['11_16', '2019-11-16'],
    ['11_15', '2019-11-15'],
    ['11_14', '2019-11-14'],
    ['11_13', '2019-11-13'],
    ['11_12', '2019-11-12'],
    ['11_11', '2019-11-11'],
    ['11_10', '2019-11-10'],
    ['11_9', '2019-11-09'],
    ['11_8', '2019-11-08'],
    ['11_7', '2019-11-07'],
    ['11_6', '2019-11-06'],
    ['11_5', '2019-11-05'],
    ['11_4', '2019-11-04'],
    ['11_3', '2019-11-03'],
    ['11_2', '2019-11-02'],
    ['11_1', '2019-11-01'],
    ['10_31', '2019-10-31'],
    ['10_30', '2019-10-30'],
    ['10_29', '2019-10-29'],
    ['10_28', '2019-10-28'],
    ['10_27', '2019-10-27'],
    ['10_26', '2019-10-26'],
    ['10_25', '2019-10-25'],
    ['10_24', '2019-10-24'],
    ['10_23', '2019-10-23'],
    ['10_22', '2019-10-22'],   
]

drop_attribs = [
        "game_date",
        'ppg_projection', 
        'value_projection', 
        "position",
        "salary", 
    
        'FantasyFuelValueProj',
        'DFN_ValueProj',
        'Proj Val'
]

In [4]:
def mergeAllDates():
    file = pd.DataFrame()
    for game_day in dates_all:
        game_date = 'HistoricalData_Merged/{}'.format(game_day[1])
        file = file.append(pd.read_csv(game_date), ignore_index=True)
    return file

def reduceForProjectionAnalysis(file):
    
    file['FantasyFuelPPGProj'] = file['ppg_projection']
    file['FantasyFuelValueProj'] = file['value_projection']
    file['DFN_PPGProj'] = file['Proj FP']
    file['DFN_ValueProj'] = file['Proj Val']
    file['Avg Proj'] = ((file['DFN_PPGProj']+file['FantasyFuelPPGProj'])/2)
    file['Avg Val'] = ((file['DFN_ValueProj']+file['FantasyFuelValueProj'])/2)
   
    file = file[file['injury_status'] != 'O']
    
    file = file.replace([np.inf, -np.inf], 0)
    file = file.fillna(0)
    file.drop(drop_attribs, axis=1, inplace=True)
    
    return file

full_df = reduceForProjectionAnalysis(mergeAllDates())

full_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18079 entries, 0 to 21983
Data columns (total 38 columns):
Player Name           18079 non-null object
injury_status         18079 non-null object
team                  18079 non-null object
opp                   18079 non-null object
spread                18079 non-null float64
over_under            18079 non-null float64
implied_team_score    18079 non-null float64
L5_dvp_rank           18079 non-null int64
L5_ppg_floor          18079 non-null float64
L5_ppg_avg            18079 non-null float64
L5_ppg_max            18079 non-null float64
Pos                   18079 non-null object
Salary                18079 non-null int64
Rest                  18079 non-null float64
USG                   18079 non-null float64
PER                   18079 non-null float64
Opp Pace              18079 non-null int64
Opp DEff              18079 non-null int64
Opp DvP               18079 non-null object
L2 FGA                18079 non-null int64
L5 FGA 

In [5]:
full_df['injury_status'].value_counts()

0    17176
Q      903
Name: injury_status, dtype: int64

In [6]:
def rmse(x,y):
    bench_mse = mean_squared_error(y, x)
    bench_rmse = np.sqrt(bench_mse)
    return bench_rmse


def benchmarks(file):
    bench_proj = full_df['Avg Proj']
    bench_actual = full_df['Actual FP']
    print('FP Proj Error: ',rmse(bench_proj, bench_actual))
    
    bench_val = full_df['Avg Val']
    bench_actual_val = full_df['Actual Val']
    print('FP Val Error: ',rmse(bench_val, bench_actual_val))
    
    bench_min = full_df['Proj Min']
    bench_actual_min = full_df['Actual Min']
    print('FP Min Error: ',rmse(bench_min, bench_actual_min))

##Benchmark
benchmarks(full_df)

FP Proj Error:  9.493387208256
FP Val Error:  2.110700577188676
FP Min Error:  6.221389807218251


In [7]:
def runLinearRegression(df, needed, label_type):
    train_set, test_set = train_test_split(df, test_size=0.2, random_state=42)
    features = train_set.drop(['Actual FP','Actual Min','Actual Val'], axis=1).copy()
    labels = train_set[label_type].copy()
    if(needed):
        features = encodeFeatures(cleanFeatures(features))
    lin_reg = LinearRegression()
    lin_reg.fit(features, labels)
    lin_scores = cross_val_score(lin_reg, features, labels, scoring='neg_mean_squared_error', cv=10)
    lin_rmse_scores = np.sqrt(-lin_scores)
    display_scores(lin_rmse_scores, label_type)
    return lin_reg.coef_

    
    
def display_scores(scores, label_type):
    print("*", label_type)
    print('Scores:', scores)
    print('Mean:' ,scores.mean())
    print('Std:', scores.std())
    

def cleanFeatures(features): 
    features['L5_ppg_floor'].fillna(0, inplace=True)
    features['L5_ppg_avg'].fillna(0, inplace=True)
    features['L5_ppg_max'].fillna(0, inplace=True)
    features['USG'].fillna(0, inplace=True)
    features['PER'].fillna(0, inplace=True)
    features['spread'].fillna(features['spread'].mean(), inplace=True)
    features['over_under'].fillna(features['over_under'].mean(), inplace=True)
    features['implied_team_score'].fillna(features['implied_team_score'].mean(), inplace=True)
    features['Rest'].fillna(features['Rest'].mean(), inplace=True)
    features['injury_status'].fillna('good', inplace=True)
    return features

def encodeFeatures(features):
    nba_player = features['Player Name']
    nba_injury = features['injury_status']
    nba_team = features['team']
    nba_opp = features['opp']
    nba_pos = features['Pos']
    nba_dvp = features['Opp DvP']
    
    nba_player_encoded, nba_player_categories = nba_player.factorize()
    nba_injury_encoded, nba_injury_categories = nba_injury.factorize()
    nba_team_encoded, nba_team_categories = nba_team.factorize()
    nba_opp_encoded, nba_opp_categories = nba_opp.factorize()
    nba_pos_encoded, nba_pos_categories = nba_pos.factorize()
    nba_dvp_encoded, nba_dvp_categories = nba_dvp.factorize()
    
    features['Player Name'] = nba_player_encoded
    features['injury_status'] = nba_injury_encoded
    features['team'] = nba_team_encoded
    features['opp'] = nba_opp_encoded
    features['Pos'] = nba_pos_encoded
    features['Opp DvP'] = nba_dvp_encoded
    return features

In [8]:
runLinearRegression(full_df, True, 'Actual FP')

* Actual FP
Scores: [9.17867227 9.21812509 9.55919006 9.18111806 9.36099607 9.21006414
 9.33155873 9.62280294 9.60825727 9.51909614]
Mean: 9.378988076576308
Std: 0.17331402026239848


array([-1.03018692e-03, -1.04856257e+00,  1.28832381e-03, -4.32934933e-03,
        4.50772578e-01, -4.27808134e-01,  8.38538060e-01,  1.23962587e-02,
       -2.08124022e-02,  3.42606203e-02,  1.57737644e-02, -1.29794034e-02,
       -7.79942756e-04, -7.74990693e-02,  4.43528276e-02, -8.74674827e-02,
       -2.87456068e-03,  4.41332608e-02, -2.24352023e-03,  1.42607241e-01,
       -1.03325588e-01, -1.95328888e-02, -8.66568240e-02,  1.92792890e-02,
        6.47776595e-02, -8.48444000e-03,  2.16140303e+00, -1.04195359e+00,
       -1.06269480e+00, -5.35605423e-02,  3.64881300e-01,  1.05368151e-01,
        3.64881300e-01,  2.35124726e-01, -1.08634227e+00])

In [9]:
runLinearRegression(full_df, True, 'Actual Val')

* Actual Val
Scores: [2.04621612 2.08657239 2.07089904 2.04551141 2.09581245 2.01292902
 2.10532786 2.09488793 2.05961717 2.11872454]
Mean: 2.073649793562047
Std: 0.030952119837504472


array([-1.74688048e-04, -2.05980396e-01,  5.03002810e-04, -1.09477248e-03,
        4.82916312e-02, -4.14059784e-02,  7.99665938e-02,  1.36849245e-03,
       -3.91068240e-03,  1.00441280e-02,  3.63636313e-03, -8.75887341e-04,
       -2.66297500e-04, -2.82056010e-02,  1.04584427e-02, -1.82969174e-02,
        1.54797348e-03,  1.10529202e-02,  4.57522649e-04,  2.65649295e-02,
       -1.29318824e-02, -1.30342825e-02, -1.66558238e-02,  2.48215147e-03,
        1.40779641e-02, -6.60403117e-03,  8.05416453e-01, -3.89726957e-01,
       -3.95985317e-01, -1.35319304e-02,  4.52834835e-02, -5.28822146e-02,
        4.52834835e-02, -3.79936555e-03,  6.37802943e-01])

In [10]:
runLinearRegression(full_df, True, 'Actual Min')

* Actual Min
Scores: [6.03935024 5.88252423 5.66149596 5.69788665 5.77029019 5.64047076
 5.69347278 5.72985873 5.91206351 5.54663123]
Mean: 5.757404426836965
Std: 0.13961358181925493


array([-2.14684611e-04, -9.24312614e-01, -5.83052345e-03, -8.56631134e-03,
        3.02310625e-01, -2.95361990e-01,  5.76382124e-01,  8.98053425e-03,
       -1.93111835e-02,  5.13732365e-02,  6.53154169e-03, -3.28820534e-02,
       -1.30327782e-03, -1.10051298e-01,  1.20693512e-02, -2.34221400e-02,
       -6.59853176e-03,  8.12074360e-03,  4.57904724e-03,  7.13484099e-02,
       -4.89478309e-02,  3.95122968e-02, -4.27920202e-02,  4.04494820e-02,
        7.64632721e-02, -3.98150830e-02,  5.89617151e-01, -2.85453380e-01,
       -3.15346140e-01,  8.07782380e-01, -3.35312080e-03,  2.02815856e-01,
       -3.35312080e-03,  9.97313677e-02, -1.67236048e+00])

In [11]:
def normalize(df):
    result = df.copy()
    for feature_name in df.columns:
        max_value = df[feature_name].max()
        min_value = df[feature_name].min()
        result[feature_name] = (df[feature_name] - min_value) / (max_value - min_value)
    return result

def standardize(df):
    result = df.copy()
    for feature_name in df.columns:
        mean_value = df[feature_name].mean()
        std_value = df[feature_name].std()
        result[feature_name] = ((df[feature_name] - mean_value) / (std_value))
    return result


In [12]:
encoded_df = encodeFeatures(cleanFeatures(full_df)).copy()

encoded_df = encoded_df[encoded_df['Avg Proj'] > 5]

runLinearRegression(encoded_df, False, 'Actual FP')

* Actual FP
Scores: [9.39726041 9.89276122 9.66333391 9.47996106 9.48749312 9.46928428
 9.70504591 9.4242289  9.70976802 9.32661218]
Mean: 9.555574900306162
Std: 0.16851158722085116


array([-2.62516711e-03, -1.43314551e+00,  3.60401528e-02,  3.70680980e-03,
        7.22077719e-01, -7.08760376e-01,  1.40329574e+00,  1.98305003e-02,
       -1.74014596e-02,  4.80170448e-02,  7.64481611e-03, -1.81774987e-02,
       -6.81070168e-04, -1.03287910e-01,  4.44819034e-02, -7.45382538e-02,
        2.54360251e-02,  4.53416163e-02,  9.35046657e-03,  1.54130889e-01,
       -5.85434037e-02, -1.02419832e-01, -8.59791039e-02, -2.34431916e-02,
        8.59558490e-02, -2.15107905e-02,  1.91005354e+00, -9.15036285e-01,
       -9.30694824e-01, -4.95788919e-03,  3.42639892e-01,  1.08649039e-01,
        3.42639892e-01,  2.25644465e-01, -8.05788475e-01])

In [13]:
encoded_df = encodeFeatures(cleanFeatures(full_df)).copy()

Index(['Player Name', 'injury_status', 'team', 'opp', 'spread', 'over_under',
       'implied_team_score', 'L5_dvp_rank', 'L5_ppg_floor', 'L5_ppg_avg',
       'L5_ppg_max', 'Pos', 'Salary', 'Rest', 'Opp Pace', 'Opp DEff',
       'Opp DvP', 'L2 FGA', 'L5 FGA', 'S FGA', 'L2 Min', 'L5 Min', 'S Min',
       'L5 FP', 'S FP', 'Floor FP', 'Ceil FP', 'Proj Min', 'Proj FP',
       'Actual Min', 'Actual FP', 'Actual Val', 'FantasyFuelPPGProj',
       'DFN_PPGProj', 'Avg Proj', 'Avg Val'],
      dtype='object')


Floor - Indicates a player’s low-end FP and is a useful measure of a player’s consistency. A player is roughly expected to exceed his floor 84% of the time. Calculated as the season average minus one standard deviation.

Ceil - Indicates a player’s high-end FP and is a useful measure of a player’s upside. A player is roughly expected to exceed his ceiling 16% of the time. Calculated as the season average plus one standard deviation.

[Value] Indicates a player’s bang for buck or salary efficiency. Calculated as the ratio of FP/(Salary/1,000).

In [18]:
relevant_df = pd.DataFrame()

#relevant_df['Pos'] = encoded_df['Pos']
relevant_df['Actual FP'] = encoded_df['Actual FP']
relevant_df['Actual Val'] = encoded_df['Actual Val']
relevant_df['Actual Min'] = encoded_df['Actual Min']

relevant_df['Avg Proj'] = encoded_df['Avg Proj']
relevant_df['Avg Val'] = encoded_df['Avg Val']
relevant_df['Proj Min'] = encoded_df['Proj Min']


relevant_df['Avg Skewed FP'] = ((encoded_df['L5 FP']+encoded_df['S FP']+encoded_df['Ceil FP']+encoded_df['Floor FP']+encoded_df['Avg Proj'])/5) 

relevant_df['Avg Skewed Min'] = ((encoded_df['L2 Min']+encoded_df['L5 Min']+encoded_df['S Min'])/3)
relevant_df['Avg L5 PPG'] = ((encoded_df['L5_ppg_floor']+encoded_df['L5_ppg_avg']+encoded_df['L5_ppg_max'])/3)
relevant_df['Avg Skewed FGA'] = ((encoded_df['L2 FGA']+encoded_df['L5 FGA']+encoded_df['S FGA'])/3)
relevant_df['USG'] = encoded_df['USG']
relevant_df['PER'] = encoded_df['PER']





relevant_df.replace([np.inf, -np.inf], 0, inplace=True)

relevant_df = relevant_df[relevant_df['Avg Proj'] > 1]
#relevant_df= normalize(relevant_df)
relevant_df= standardize(relevant_df)


In [19]:
relevant_df.dropna(inplace=True)

In [20]:
corr_matrix = relevant_df.corr()

In [21]:
corr_matrix.style.background_gradient(cmap='coolwarm')



In [65]:
runLinearRegression(relevant_df, False, 'Actual FP')

* Actual FP
Scores: [0.64443226 0.64599153 0.63991645 0.6419117  0.63048614 0.64535319
 0.6461138  0.64381635 0.63331027 0.62832469]
Mean: 0.639965637971562
Std: 0.006413826492706386


array([ 0.60633161, -0.0507102 ,  0.11853793,  0.14131518, -0.10888897,
       -0.0043658 ,  0.02304646,  0.03669841, -0.01879682, -0.02900266,
        0.0486722 , -0.01128621])

In [66]:
relevant_df.head()



Actual FP  Actual Val  Actual Min  Avg Proj   Avg Val  Proj Min  \
0   2.071633    0.150233    1.589633  3.006682  0.736702  1.256989   
1   2.717956    0.666047    1.419619  2.481768  0.497599  1.305920   
2   1.275635   -0.064689    1.009586  2.084983  0.403526  0.816612   
3   2.173684    0.322171    0.309530  2.031252  0.066430  0.571959   
4   1.683839    0.322171    1.749646  1.857659  0.438803  1.159128   

   Avg Skewed FP  Avg Skewed Min  Avg L5 PPG  Avg Skewed FGA       USG  \
0       3.044986        1.355442    2.765612        2.811695  2.692690   
1       2.434565        1.317449    1.661682        2.286215  2.318609   
2       2.117861        0.975520    1.974695        0.841148  1.321061   
3       2.411579        1.013512    1.720371        2.023476  1.819835   
4       1.732198        1.545402    1.203341        1.169572  0.572900   

        PER  Proj FPP Per Min  Proj Min Enhanced  Proj Pts Scores  
0  2.246841          2.287757           2.740461         2.559706  
1  1.641614          1.717731           2.360333         2.556396  
2  1.792920          1.940583           1.790240         1.314153  
3  1.944227          2.255932           1.441722         1.799135  
4  1.641614          1.271339           1.465863         0.733851